// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Appointment struct {
	ApptDate        string `json:"apptDate"`
	StartTime       string `json:"startTime"`
	EndTime         string `json:"endTime"`
	PaymentType     string `json:"paymentType"`
	ClientCancelled bool   `json:"clientCancelled"`
	BarberCancelled bool   `json:"barberCancelled"`
}

type Barber struct {
	BarberID    string  `json:"barberID"`
	ShopID      int     `json:"shopID"`
	UserName    string  `json:"userName"`
	Password    string  `json:"password"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	PhoneNumber string  `json:"PhoneNumber"`
	Gender      *string `json:"gender"`
	Dob         string  `json:"dob"`
	HireDate    string  `json:"hireDate"`
	DismissDate *string `json:"dismissDate"`
	SeatNum     int     `json:"seatNum"`
}

type BarberAppointment struct {
	Barber      *Barber      `json:"barber"`
	Shop        *Shop        `json:"shop"`
	Appointment *Appointment `json:"appointment"`
	Client      *MinClient   `json:"client"`
	Service     *Service     `json:"service"`
}

type DateRange struct {
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

type MinClient struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type NewBarber struct {
	ShopID      int     `json:"shopID"`
	UserName    string  `json:"userName"`
	Password    string  `json:"password"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	PhoneNumber string  `json:"PhoneNumber"`
	Gender      *string `json:"gender"`
	Dob         string  `json:"dob"`
	HireDate    string  `json:"hireDate"`
	DismissDate *string `json:"dismissDate"`
	SeatNum     int     `json:"seatNum"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Response struct {
	Response string `json:"response"`
	Error    string `json:"error"`
}

type Service struct {
	ServiceName        string  `json:"serviceName"`
	ServiceDescription string  `json:"serviceDescription"`
	Price              float64 `json:"price"`
	Duration           int     `json:"duration"`
}

type Shop struct {
	ShopName   string `json:"shopName"`
	StreetAddr string `json:"streetAddr"`
}

type UserLogin struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
